### ISSUE TITLE
Upstreaming tracker

### ISSUE THREAD

**Issue by mgehre-amd** [Xilinx/torch-mlir#70]
Tracks our progress of upstreaming fixes in this repository

Not related to TOSA:
- [ ] #40
- [ ] #50
- [ ] #60
- [ ] #63 + #129
- [ ] #44 + #96 + #109 + #111
- [x] #118
- [ ] #128 

Purely TorchToTOSA:
- [x] bf16 dfixes -> https://github.com/llvm/torch-mlir/pull/2239
- [ ] #28 (aten.to_dtype bf16/f64/i64, see function TorchToTosa)
- [x] #20 -> https://github.com/llvm/torch-mlir/pull/2205
- [x] #19 -> https://github.com/llvm/torch-mlir/pull/2307
- [ ] #17 (The non-TOSA parts already landed upstream)
- [x] #18 -> https://github.com/llvm/torch-mlir/pull/2234
- [x] #23 -> https://github.com/llvm/torch-mlir/pull/2210
- [x] #29 -> https://github.com/llvm/torch-mlir/pull/2204
- [x] #36 -> https://github.com/llvm/torch-mlir/pull/2304
- [x] #22 + #37 + #87 -> https://github.com/llvm/torch-mlir/pull/2314
- [x] #38
- [x] #45 -> https://github.com/llvm/torch-mlir/pull/2200
- [ ] #47
- [ ] #58 (Lower aten.atan2 to tosa.custom)
- [ ] #55
- [ ] #61
- [ ] #64
- [ ] #62
- [x] #65 -> https://github.com/llvm/torch-mlir/pull/2198
- [x] #66 -> https://github.com/llvm/torch-mlir/pull/2240
- [ ] #67
- [x] #68 -> https://github.com/llvm/torch-mlir/pull/2209
- [ ] #72
- [x] #77 -> https://github.com/llvm/torch-mlir/pull/2327
- [ ] #78
- [ ] #79
- [ ] #80
- [ ] #81
- [ ] #82
- [ ] #83 + #84
- [ ] #85
- [ ] #86
- [ ] #88 
- [ ] #89 
- [ ] #94 
- [ ] #95 
- [ ] #97 
- [ ] #98
- [x] #113 -> https://github.com/llvm/torch-mlir/pull/3476
- [x] #115 
- [ ] #116 
- [x] #124 -> https://github.com/llvm/torch-mlir/pull/2328
- [x] #125
- [x] #126 -> https://github.com/llvm/torch-mlir/pull/2329
